### ISSUE TITLE
Rows hidden after postback when DDL filters applied

### ISSUE THREAD

**Issue by iwdev5** [PicNet/tablefilter#24]
When a Drop-down-list filter is applied to a table, the rows are filtered correctly and anything that does not match is hidden,

However, when the page is posted back to the server and the table filter is re-initialized using the filters from the cookie, all the table rows are hidden and the drop down combo box does not have filter value selected. 

It appears that the matchingRow functionality is working correctly but there's something happening near the end of processing that causes all rows to be hidden.

**Comment by henla464** [comment]
Hi,

I tried to reproduce your problem with rows being hidden but couldn't. I did see however that the filter value wasn't set in the combo box after postback (in Chrome, worked in IE). I fixed that problem, can you download latest version from github and test again. If the hidden rows problem is still there, could you provide a test example to show me the problem (perhaps by modifying the demoSrc.html page)? Also when it happens, check the filter values saved in the cookie (you can use the extension "Edit this cookie" in chrome) so that they look correct.

Thanks for reporting this issue.

**Comment by henla464** [comment]
Hello,

Is this still an issue or can I close it?
